name: Deploy React App to GitHub Pages with Debug Logs

on:
  push:
    branches:
      - main  # change if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Show Node & npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          npm install
          echo "Files after npm install:"
          ls -lah
          ls -lah node_modules

      - name: Build app with Parcel (verbose)
        run: |
          npx parcel build src/index.html --dist-dir docs --public-url /receipt-ocr-test/ --log-level verbose
          echo "Files after build:"
          ls -lah docs

      - name: Show first 20 lines of index.html
        run: head -20 docs/index.html

      - name: Create .nojekyll file to disable Jekyll on GitHub Pages
        run: echo > docs/.nojekyll

      - name: Show docs folder before deploy
        run: ls -Rlah docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
